export const paths = {
  landing: '/',
  login: '/login',
  signup: '/signup',
  verifyEmail: '/verify-email',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  dashboard: '/app',
  tasks: '/app/tasks',
  goals: '/app/goals',
  pomodoro: '/app/pomodoro',
  rewards: '/app/rewards',
  analytics: '/app/analytics',
  aiCoach: '/app/ai-coach',
  profile: '/app/profile',
} as const;
