spring.application.name=ai-study-coach

spring.datasource.url=jdbc:postgresql://localhost:5432/AIStudyCoachDB
spring.datasource.username=postgres
spring.datasource.password=0264
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=9931ce7f56a459a34b27d2da7bcdc99a7a67ed14f895b1e230376e98b0964b85
jwt.expiration=

logging.level.org.springframework.security=INFO
logging.level.com.aistudycoach=DEBUG
logging.level.org.hibernate.SQL=INFO
